# Generated by Django 2.2.11 on 2021-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.TextField()),
                ('email', models.TextField()),
                ('bio', models.TextField()),
                ('location', models.TextField()),
                ('online', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('current_chat', models.IntegerField(blank=True, null=True)),
                ('ontime', models.DateTimeField(null=True)),
            ],
        ),
    ]
